#define OPCODE_NOW 1
#define OPCODE_EQU 2
#define OPCODE_NEQ 3
#define OPCODE_GTR 4
#define OPCODE_LSR 5
#define OPCODE_GTE 6
#define OPCODE_LSE 7
#define OPCODE_ADD 8
#define OPCODE_SUB 9
#define OPCODE_MUL 10
#define OPCODE_DIV 11
#define OPCODE_DIS 12
#define OPCODE_LN 13
#define OPCODE_EXP 14
#define OPCODE_LOG 15
#define OPCODE_E10 16
#define OPCODE_SYN 17
#define OPCODE_INS 18
#define OPCODE_APP 19
#define OPCODE_RED 20
#define OPCODE_NOTRED 21
#define OPCODE_COM 22
#define OPCODE_SPL 23
#define OPCODE_MRG 24
#define OPCODE_RPL 25
#define OPCODE_PTC 26
